portal/urls.py
from django.contrib import admin
from django.urls import path, include

# Load static files
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('order.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Customization `header`, `site-title`, and `index`
admin.site.site_header = 'Portal'
admin.site.site_title = 'Portal'
admin.site.index_title = 'Welcome to my admin portal'

user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    # Auth
    path('signin/', views.SignInView.as_view(), name='signin'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('signout/', views.SignOutView.as_view(), name='signout'),
    path('profile/', views.profile_update_view, name='profile'),
    path('password-change/', views.change_password, name='password_change'),
    path('activate/<uidb64>/<token>/', views.ActivateAccount.as_view(), name='activate'),
    path('registration-done/', views.AccountCreateSuccessView.as_view(), name='registration_done'),
    path('auth-lock-screen/', views.AuthLockScreenView.as_view(), name='auth_lock_screen'),
    path('logout-lock-screen/', views.SignOutScreenLockView.as_view(), name='logout_lock_screen'),
    # Rest or forgot password
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='auth/password_reset.html'),
         name='reset_password'),
    path('password_reset_done/',
         auth_views.PasswordResetDoneView.as_view(template_name='auth/password_reset_done.html'),
         name='password_reset_done'),
    path('user/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='auth/set_password.html'),
         name='password_reset_confirm'),
    path('user/password_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='auth/password_reset_complete.html'),
         name='password_reset_complete'),
    # Users
    path('users/', views.UserListView.as_view(), name='users'),
    path('create-user/', views.UserCreateByAdminView.as_view(), name='create_user'),
    path('update-user/<pk>/', views.UserUpdateViewFormAdmin.as_view(), name='update_user'),
    path('user-delete/<pk>/', views.UserDeleteView.as_view(), name='user_delete'),
]

order/models.py
from django.db import models
from user.models import User, Timestamp

from utils.enums import Status


class Service(Timestamp):
    name = models.CharField(max_length=200)
    notes = models.TextField(default='')
    is_active = models.BooleanField(default=True)
    icon = models.ImageField(default='service/%m/%y', blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def __str__(self):
        return self.name


class Workflow(Timestamp):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Preference(Timestamp):
    name = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class FileFormate(Timestamp):
    name = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Order(Timestamp):
    job_title = models.CharField(max_length=150)
    exit_meta_date = models.BooleanField(default=False)
    preference = models.ManyToManyField(Preference, related_name='orderPreference')
    file_formate = models.ManyToManyField(FileFormate, related_name='orderFileFormate')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orderBy')
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='orderService')
    work_process = models.ForeignKey(Workflow, on_delete=models.CASCADE, related_name='orderWord')
    status = models.IntegerField(choices=Status.get_status(), default=Status.PENDING.value)
    quantity = models.IntegerField(default=1)
    instruction = models.TextField(default='')
    download_link = models.URLField()

    def __str__(self):
        return self.service.name
    
    @property
    def get_user(self):
        return self.user.name

    @property
    def total_price(self):
        return self.quantity * self.service.price

user/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser

from utils.enums import UserTypes
from user.manager import UserManager


class Timestamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]
        abstract = True


class User(AbstractUser, Timestamp):
    username = None
    name = models.CharField(max_length=150)
    email = models.EmailField(max_length=200, unique=True)
    phone = models.CharField(max_length=15, unique=True)
    role = models.IntegerField(choices=UserTypes.get_choices(), default=UserTypes.USER.value)

    def __str__(self):
        return self.name

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["name", "phone"]

    objects = UserManager()


class Profile(Timestamp):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    company_name = models.CharField(max_length=200, blank=True, null=True, default="")
    street = models.CharField(max_length=200, blank=True, null=True, default="")
    city = models.CharField(max_length=200, blank=True, null=True, default="")
    state = models.CharField(max_length=200, blank=True, null=True, default="")
    zip_code = models.IntegerField(blank=True, null=True, default=1230)
    avatar = models.ImageField(upload_to="profile/%m/%d", blank=True, null=True)

    def __str__(self):
        return self.user.name


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = Profile.objects.get_or_create(user=instance)
        return profile


post_save.connect(create_user_profile, sender=User)

user/views.py
from django.urls import reverse
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.views import View, generic
from django.shortcuts import resolve_url
from django_filters.views import FilterView
from django.shortcuts import redirect, render
from django.contrib.auth.views import LoginView
from django.template.loader import render_to_string
from django.utils.decorators import method_decorator
from django.contrib.auth.forms import PasswordChangeForm
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import login, logout, update_session_auth_hash
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

from user import forms
from .models import User
from utils.tokens import account_activation_token


class SignUpView(View):
    """
    Name: User signUP view
    URL: /user/signup/
    Method: POST
    """
    form_class = forms.SingUpForm
    template_name = 'auth/signup/signup.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False  # Deactivate account till it is confirmed
            user.save()

            current_site = get_current_site(request)
            subject = 'Activate Your MySite Account'
            message = render_to_string('auth/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            send_mail(
                subject=subject,
                message=message,
                from_email=settings.EMAIL_HOST_USER,
                html_message=message,
                recipient_list=[user.email]
            )
            messages.success(request, 'Please Confirm your email to complete registration.')
            return redirect('registration_done')
        return render(request, self.template_name, {'form': form})


class AccountCreateSuccessView(View):
    """
    Registration done show success page and instructions page
    """

    def get(self, reqeust, *args, **kwargs):
        template_name = 'auth/signup/registration_done.html'
        return render(reqeust, template_name)


class ActivateAccount(View):
    """
    After registration send mail and activate account.
    """

    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            login(request, user)
            messages.success(request, 'Your account have been confirmed.')
            return redirect('signin')
        else:
            messages.warning(request, 'The confirmation link was invalid, possibly because it has already been used.')
            return redirect('signin')


class SignInView(LoginView):
    """
    Name: User SignIn view
    URL: /user/signin/
    :param
    email
    password
    """
    authentication_form = forms.LoginForm
    form_class = forms.LoginForm
    redirect_authenticated_user = False
    template_name = 'auth/signin/signin.html'

    def get_success_url(self):
        url = self.get_redirect_url()
        return url or resolve_url('/dashboard/')

    def form_valid(self, form):
        remember_me = form.cleaned_data['remember_me']
        login(self.request, form.get_user())

        if remember_me:
            self.request.session.set_expiry(1209600)
        return super(SignInView, self).form_valid(form)


class SignOutView(View):
    """
    Name: Logout view
    URL: signout/
    """

    def get(self, request):
        logout(request)
        return redirect('/user/signin/')


@login_required
def change_password(request):
    """
    Password Change
    :param request:
    :return:
    URL: user/password_change/
    """
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('password_change')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'auth/change_password.html', {
        'form': form
    })


@login_required
def profile_update_view(request):
    """
    Desc: User profile update view
    :param request:
    :return:
    """
    if request.method == 'POST':
        u_form = forms.UserUpdateModelForm(request.POST, instance=request.user)
        p_form = forms.ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, "Your profile updated successfully.")
            return redirect('profile')
        else:
            messages.error(request, "Something went to error.")
            return redirect('profile')
    else:
        u_form = forms.UserUpdateModelForm(instance=request.user)
        p_form = forms.ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    template_name = 'auth/profile/profile.html'
    return render(request, template_name, context)


@method_decorator(login_required(login_url='/user/signin/'), name='dispatch')
class AuthLockScreenView(LoginView):
    """
    Name: Auth lock screen login without username.
    :param
    password
    """
    template_name = 'auth/auth_lock_screen.html'
    authentication_form = forms.LoginForm
    form_class = forms.LoginForm
    redirect_authenticated_user = False

    def get_success_url(self):
        url = self.get_redirect_url()
        return url or resolve_url('/dashboard/')

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(AuthLockScreenView, self).form_valid(form)


@method_decorator(login_required(login_url='/user/signin/'), name='dispatch')
class SignOutScreenLockView(View):
    """
    Name: Lock screen view
    URL: user/lock-screen/
    """

    def get(self, request):
        currentpassword = request.user.password
        currentpassword.replace(request.user.password, '')
        return redirect('/user/auth-lock-screen/')


@method_decorator(login_required(login_url='/user/signin/'), name='dispatch')
class UserListView(FilterView, generic.ListView):
    """List of users with filter"""
    model = User
    paginate_by = 8
    context_object_name = 'users'
    template_name = 'users/users.html'
    filterset_fields = ['name', 'email', 'phone', 'role']


@method_decorator(login_required(login_url='/user/signin/'), name='dispatch')
class UserCreateByAdminView(SuccessMessageMixin, generic.CreateView):
    """
    User creating using CMS
    """
    model = User
    form_class = forms.CreateUserByAdminForm
    success_url = '/user/create-user/'
    success_message = 'User created successfully.'
    template_name = 'users/create_user.html'

    def form_valid(self, form):
        cd = form.cleaned_data
        email_to = cd['email']
        subject = "{0} Login credentials ".format(cd['email'])
        mes = "Welcome to Cutout portal new member! Please check below your login credentials for login in your account."
        message = f"{mes}\n\nEmail Address: {cd['email']}\nPassword: {cd['password1']}"
        send_mail(subject, message, settings.EMAIL_HOST, [email_to, ])
        return super().form_valid(form)


@method_decorator(login_required(login_url='/user/signin/'), name='dispatch')
class UserUpdateViewFormAdmin(SuccessMessageMixin, generic.UpdateView):
    """
    Super admin can update any user
    """
    model = User
    form_class = forms.UserUpdateForm
    success_message = 'User has been updated.'
    template_name = 'users/update_user.html'

    def get_success_url(self):
        return reverse('update_user', kwargs={'pk': self.object.id})


@method_decorator(login_required(login_url='/user/signin/'), name='dispatch')
class UserDeleteView(SuccessMessageMixin, generic.DeleteView):
    """
    User can delete from CMS
    """
    model = User
    success_url = '/user/users/'
    success_message = 'The use has been deleted.'
    template_name = 'common/delete_confirm.html'

user/templates/users/create_user.html
{% extends 'base.html' %}

{% block title %} Create new user {% endblock %}

{% block content %}
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                <h4 class="mb-sm-0 font-size-18">User</h4>
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Create user</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- end page title -->
    <div class="row">
        <div class="col-xl-12 col-md-12">
            <!-- card -->
            <div class="card card-h-100">
                <!-- card body -->
                <div class="card-body">
                    <form method="post" name="registrationForm">
                        {% include 'common/message/success_msg.html' %}
                        {% if forms.errors %}
                            {% include 'common/message/error_msg.html' %}
                        {% endif %}
                        {% csrf_token %}
                        <div class="mb-3" style="display: grid; grid-gap: 15px; grid-template-columns: 1fr 1fr">
                            <div class="form-group">
                                <label for="id_name">Fullname</label>
                                <input type="text" id="id_name" name="name" class="form-control"
                                       placeholder="Enter fullname" required>
                            </div>
                            <div class="form-group">
                                <label for="id_email">Email Address</label>
                                <input type="email" id="id_email" name="email" class="form-control"
                                       placeholder="Enter email address" required>
                            </div>
                            <div class="form-group">
                                <label for="id_phone">Phone Number</label>
                                <input type="tel" id="id_phone" name="phone" class="form-control"
                                       placeholder="Enter phone number" required>
                            </div>
                            <div class="form-group">
                                <label for="role_id">User Role</label>
                                <select class="form-select" name="role" id="role_id">
                                    <option>Select Role</option>
                                    <option value="1">General user</option>
                                    <option value="2">Manager</option>
                                    <option value="3">Admin</option>
                                </select>
                            </div>
                            <div style="position: relative;" class="form-group">
                                <label for="id_password1">Password</label>
                                <span onClick="randomPassword(10);"
                                      style="position: absolute; right: 5px; cursor: pointer">Generate Random Password</span>
                                <input type="password" id="id_password1" name="password1" class="form-control"
                                       placeholder="*************" required/>
                                <button style="position:absolute; right: 0; top: 28px"
                                        class="btn btn-light shadow-none ms-0" type="button" id="password-addon"><i
                                        class="mdi mdi-eye-outline"></i></button>
                            </div>
                            <div style="margin-top: 28px" class="form-check form-switch form-switch-lg">
                                <label class="form-check-label" for="id_is_active">Active Status</label>
                                <input type="checkbox" class="form-check-input" name="is_active" id="id_is_active"/>
                            </div>
                        </div>
                        <div class="mt-3">
                            <button type="submit" class="btn btn-success btn-sm">Create User</button>
                            <a href="{% url 'users' %}" class="btn btn-info btn-sm">Back</a>
                        </div>
                    </form>
                </div><!-- end card body -->
            </div><!-- end card -->
        </div><!-- end col -->
    </div><!-- end row-->
    <script>
        // Generate random password
        function randomPassword(length) {
            let chars = "abcdefghijklmnopqrstuvwxyz!@#$%^&*()-+<>ABCDEFGHIJKLMNOP1234567890";
            let pass = "";
            for (let x = 0; x < length; x++) {
                let i = Math.floor(Math.random() * chars.length);
                pass += chars.charAt(i);
            }
            registrationForm.password1.value = pass;
        }
    </script>
{% endblock %}

user/templates/users/filter.html
<form class="search_filter_item" method="get">
    <div style="display: grid; grid-template-columns: 2fr 2fr 2fr 2fr 1fr; grid-gap: 10px">
        <div class="form-group">
            <label>Name</label>
            {{ filter.form.name }}
        </div>
        <div class="form-group">
            <label>Email</label>
            {{ filter.form.email }}
        </div>
        <div class="form-group">
            <label>Phone Number</label>
            {{ filter.form.phone }}
        </div>
        <div class="form-group">
            <label>Role</label>
            {{ filter.form.role }}
        </div>
        <button style="height: 40px; margin-top: 25px" class="btn btn-success" type="submit">Search</button>
    </div>
</form>

user/templates/users/update_user.html
{% extends 'base.html' %}

{% block title %} Update user information {% endblock %}

{% block content %}
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                <h4 class="mb-sm-0 font-size-18">User</h4>
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Dashboard</a></li>
                        <li class="breadcrumb-item active">Update user</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- end page title -->
    <div class="row">
        <div class="col-xl-12 col-md-12">
            <!-- card -->
            <div class="card card-h-100">
                <!-- card body -->
                <div class="card-body">
                    <form method="post">
                        {% include 'common/message/success_msg.html' %}
                        {% if forms.errors %}
                            {% include 'common/message/error_msg.html' %}
                        {% endif %}
                        {% csrf_token %}
                        <div class="mb-3" style="display: grid; grid-gap: 15px; grid-template-columns: 1fr 1fr">
                            <div class="form-group">
                                <label for="id_name">Fullname</label>
                                {{ form.name }}
                            </div>
                            <div class="form-group">
                                <label for="id_email">Email Address</label>
                                {{ form.email }}
                            </div>
                            <div class="form-group">
                                <label for="id_phone">Phone Number</label>
                                {{ form.phone }}
                            </div>
                            <div class="form-group">
                                <label for="role">User Role</label>
                                {{ form.role }}
                            </div>
                            <div class="form-check form-switch form-switch-lg">
                                <label class="form-check-label" for="is_active">Active Status</label>
                                {{ form.is_active }}
                            </div>
                        </div>
                        <div class="mt-3">
                            <button type="submit" class="btn btn-success btn-sm">Update User</button>
                            <a href="{% url 'users' %}" class="btn btn-info btn-sm">Back</a>
                        </div>
                    </form>
                </div><!-- end card body -->
            </div><!-- end card -->
        </div><!-- end col -->
    </div><!-- end row-->
{% endblock %}

user/templates/users/users.html
{% extends 'base.html' %}

{% block title %} Users {% endblock %}

{% block content %}
    <!-- start page title -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                <h4 class="mb-sm-0 font-size-18">Users</h4>
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Dashboard</a></li>
                        <li class="breadcrumb-item active">List of users</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!-- end page title -->
    <div class="row mb-3">
        {% include 'users/filter.html' %}
    </div>
    <div class="row">
        <div class="col-md-12">
            {% include 'common/message/success_msg.html' %}
            {% if users %}
                <div class="table-responsive">
                    <table class="table table-striped table-bordered border-success mb-0">
                        <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Phone Number</th>
                            <th>Role</th>
                            <th>Status</th>
                            <th>Created At</th>
                            <th class="text-center">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for obj in users %}
                            <tr>
                                <td>{{ obj.name }}</td>
                                <td>{{ obj.email }}</td>
                                <td>{{ obj.phone }}</td>
                                <td>{{ obj.get_role_display.title }}</td>
                                <td>{% if obj.is_active %} Active {% else %} Deactivate {% endif %}</td>
                                <td>{{ obj.created_at.date }}</td>
                                <td class="text-center">
                                    <a class="btn btn-success btn-sm" href="{% url 'update_user' obj.pk %}"><i
                                            class="mdi mdi-pencil"></i></a>
                                    <a class="btn btn-danger btn-sm" href="{% url 'user_delete' obj.pk %}"><i
                                            class="mdi mdi-trash-can"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <div class="text-center">
                    <p>No user found.</p>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}